# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:20-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package files and install the dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN npm run build

# Use a minimal Node.js image for the final build
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy built files and node_modules from the builder
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Expose any ports the app is expected to listen on
# EXPOSE <port_number>

# Set environment variables (if any)
ENV COSENSE_PROJECT_NAME=your_project_name
# ENV COSENSE_SID=your_sid

# Run the server
ENTRYPOINT ["node", "build/index.js"]